### PR TITLE
- enable auto creation of links when pasting a link on a highlighted …

### PR DESCRIPTION
**Pull request by avramz**
This PR adds an additional option, `magicPasteLinks`. 
When enabled, if valid URL is pasted, the selected text will automatically be linked to it.

### CODE REVIEW

**Comment by artem-schander** [comment]
Hi @avramz 
Thank you for your contribution. It's very appreciated.
I like the Idea and will most likely merge it as soon as I looked into the implementation.

**Comment by avramz** [comment]
Thank you!

**Review by artem-schander — APPROVED** [review]

**Comment by artem-schander** [comment]
Unfortunately your regex did not work for me. I have no Idea what went wrong. I've changed it to [@diegoperini](https://mathiasbynens.be/demo/url-regex).
Nice work anyway.
It's published now  -> [v1.3](https://www.npmjs.com/package/quill-paste-smart/v/1.3.0)

---
#### EDIT
I have also made it only work if links are allowed.
Here is a [CodeSandbox](https://codesandbox.io/s/vanilla-es6-quill-paste-smart-forked-m7gfd?file=/quill-paste-smart.js) to play around and see if everything works well.

**Comment by avramz** [comment]
Awesome, thanks a lot man!

**Pull request merged**
