### PR TITLE
Update to quill 2

### PR DESCRIPTION
**Pull request by jonmarozick**
Update peer dependency to quill 2.0.2.
Remove support for old IE since quill 2 [does not support it](https://quilljs.com/docs/upgrading-to-2-0#browser).
Removed work around for [quill bug 3333](https://github.com/slab/quill/issues/3333)

I did not update the dist folder with a new minified file. I did an npm install and npm run build but I got an error
```
ERROR in quill-paste-smart.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
```

This should address [Issue 34](https://github.com/Artem-Schander/quill-paste-smart/issues/34)

### CODE REVIEW

**Comment by enzedonline** [comment]
Hi,

Thanks for working on this.

I've just tried this out, unfortunately nothing getting pasted unless I choose 'Paste as plain text' when using the default config.

I added the following in my config:
```
        clipboard: {
            allowed: {
                tags: ['a', 'b', 'strong', 'u', 's', 'i', 'p', 'br', 'ul', 'ol', 'li', 'span'],
                attributes: ['href', 'rel', 'target', 'class']
            },
            keepSelection: true,
            substituteBlockElements: true,
            magicPasteLinks: true,
            hooks: {
                uponSanitizeElement(node, data, config) {
                    console.log(node);
                },
            },

            handleImagePaste(image) {
                console.log("Image file pasted", image);
            }
        },
   ```
   I can see the pasted values in the console but nothing pasted to the editor.

Incidentally, I needed a couple of tweaks to the package config to get it to build:

In package.json:
```
  "scripts": {
    "build": "webpack --openssl-legacy-provider"
  },
```
Or maybe it should just use later versions of webpack/terser - was there a reason for these older versions? These older versions are not compatible with openSSL 3 apparently.

In webpack.config.js:
```
const TerserPlugin = require('terser-webpack-plugin');
const config = {
  ....
  optimization: {
    minimize: true,
    minimizer: [
      new TerserPlugin()
    ],
  },
  ....
  },
```

**Comment by enzedonline** [comment]
I tracked down the error to [L111](https://github.com/Artem-Schander/quill-paste-smart/blob/60fa252d41cb449cafcda15b9602b33702c97944/src/module.js#L111)

This needs to use `this.convertHTML(content)`. Once I made that change, everything so far seems to paste ok.

Support for `'table'` seems to have been left off the original package, I added that to `getDOMPurifyOptions()` in my test code which got that working.
```javascript
          case 'table':
            if (undefinedTags) {
              tidy.ALLOWED_TAGS.push('table');
              tidy.ALLOWED_TAGS.push('tr');
              tidy.ALLOWED_TAGS.push('td');
            }
            if (undefinedAttr) {
              tidy.ALLOWED_ATTR.push('width');
            }
            break;
```
(I've added an extra class method to convert table headers to standard table cells on mine - I can share that here if you like)

The issue I have remaining is that images get pasted twice for some reason. One is with src = the original url, another with the image converted to an embed (src = data:image/jpeg:base64 ...). Might be a conflict with [quill-image-compress](https://www.npmjs.com/package/quill-image-compress) - I'll look at that tomorrow.

**Comment by artem-schander** [comment]
Hi guys, thanks for all the effort. I really appreciate it.

@enzedonline 
> Or maybe it should just use later versions of webpack/terser - was there a reason for these older versions? These older versions are not compatible with openSSL 3 apparently.

No, there was no specific reason (apart from it being the latest version at the time of creating this package)

**Comment by jonmarozick** [comment]
I updated the devDependencies to the latest and I was able to compile. So, I pushed an update with the optimized code in the dist folder.

I missed the change in quill in the [convert function](https://github.com/slab/quill/blob/5d752e3fa8155a9b1ea1ddd99a9ae2d9a04f0ade/packages/quill/src/modules/clipboard.ts#L101). Updated that too.

**Comment by enzedonline** [comment]
The double image issue was caused by a clash with quill-image-compress. It went away when I defined a handleImagePaste in the options, even though it's only called when the source is file and not html. I can't work that out but I'm fine with that ...

**Comment by jonmarozick** [comment]
Unless anyone has anything else, let's merge the PR and publish a new npm package.

**Comment by enzedonline** [comment]
I have some additions around supporting tables and custom toolbar buttons. You can add those to your PR, or I could make a separate one as you like.

**Comment by jonmarozick** [comment]
@enzedonline Send me the additions and I can include them

**Comment by enzedonline** [comment]
I've uploaded to a fork [here](https://github.com/enzedonline/quill-paste-smart).

**In module.js:**

'img' and 'video'
In `getDOMPurifyOptions()`, added height & width to img and video allowed attributes.

Table support - 2 parts:
added 'table' to `getDOMPurifyOptions()` (allow 'table', 'tr' & 'td')
added `tableHeadersToCells()` class method and call in `onCapturePaste()` before purify if 'table' in allowed tags (Quill strips out table headers, this method converts row & column header cells to standard cells).

Custom button support:
`this.customButtons = options.customButtons;` added to constructor
code added at end of `getDOMPurifyOptions()` to check for and add tags/attributes according to `customButtons` setting

Expected construct for `customButtons`:
```javascript
customButtons: [
  {
    module: 'quill-some-custom-module',
    allowedTags: ['tag1', 'tag2', ...],
    allowedAttr: ['attr1', 'attr2', ...]
  },
  ...
]
```

**In README.md**
Updated for instructions on `customButtons` option

**Comment by jonmarozick** [comment]
@enzedonline I added everything from your fork. Let me know if I missed something.

**Comment by enzedonline** [comment]
Great, thank you :) 

I noticed table and tfoot had been removed from `substitute.blockElements` - made me realise that `'tr'` should be included in that list otherwise the table contents get pasted as a continuous string on a single line if `'table'` isn't included in allowed tags. Including `'tr'` pastes each table row contents as a new line.

When I tested that, I then realised that `tableHeadersToCells()` should be called regardless of whether `'table'` is allowed so that table contents are pasted consistently, otherwise header cells are dropped from the pasted content. 

If you're in agreement:

- at L106, take out the `if` clause so that `tableHeadersToCells()` always runs.
- at L371, insert `'tr'` as a block element.

**Comment by jonmarozick** [comment]
@enzedonline I removed the `if` and added the `tr`. I added `table` and `tfoot` back. And I addressed the spacing issue I had with a new `removeConsecutiveSubstitutionTags` setting.

**Comment by enzedonline** [comment]
Nice. That works well. There did seem to be a lot of extra paragraphs being inserted. It's much cleaner now.

Table pasting (when 'table' isn't allowed) still seems to be a pain. 

I looked at a table substitution, it seems the `<tr>` does not get wrapped in `<p>`, just multiple `<p></p>` tags are inserted in between. This is the substitution html for a 3 line table:
```html
<p></p><p></p>
Elementh6bodyh5h4h3h2h1
<p></p><p></p>
Minimum0.901.001.201.401.601.802.00
<p></p><p></p>
Maximum1.001.101.451.802.102.452.75
<p></p><p></p>
```
When `collapseConsecutiveSubstitutionTags()` is run on that, it ends up as one long string again since every `<p></p>` is stripped. The `<td>`'s getting concatenated without intervening spaces isn't practical either.

Fingers crossed, last change - rather than wrestle the substitution code, I've added a `convertTableContent()` method that is run from `OnCapturePaste` in the case that `'table'` in not in allowed tags. This converts the `<tr>`'s to `<p>`'s and inserts a space between each table cell on the row. Each cell (`<td>` & `<th>`) is replaced by its innerHTML. It also handles the rare cases that a partial table fragment is passed and there are orphan table cells.

```javascript
  OnCapturePaste(e) {
    ....
        if (DOMPurifyOptions.ALLOWED_TAGS.includes('table')) {
          // Convert table headers to cells
          html = this.tableHeadersToCells(html);
        } else {
          // Convert rows and cells to block and inline content 
          html = this.convertTableContent(html);
        }
    ...
  }
```

```javascript
  convertTableContent(html) {
    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = html;

    // Convert <tr> elements to <p> elements, concatenate td & th cell contents with inner space added
    Array.from(tempDiv.querySelectorAll('tr')).forEach(tr => {
      tr.outerHTML = `<p>${Array.from(tr.querySelectorAll('td, th')).map(cell => cell.innerHTML).join(' ')}</p>`
    });

    // Convert orphan td & th elements to their innerHTML plus trailing space
    Array.from(tempDiv.querySelectorAll('td, th')).forEach(cell => {
      cell.outerHTML = `${cell.innerHTML} `;
    });

    return tempDiv.innerHTML;
  }
```

Now, when I paste the same table, the substitution html comes back as:
```html
<p>Element h6 body h5 h4 h3 h2 h1</p>
<p>Minimum 0.90 1.00 1.20 1.40 1.60 1.80 2.00</p>
<p>Maximum 1.00 1.10 1.45 1.80 2.10 2.45 2.75</p>
```

**Comment by jonmarozick** [comment]
I tried out that code on this html.

```
<html>

<head>
    <meta http-equiv=Content-Type content="text/html; charset=utf-8">
</head>

<body lang=EN-US>
    <table>
        <thead>
            <tr>
                <th>thead-tr-th 1</th>
                <th>thead-tr-th 2</th>
                <th>thead-tr-th 3</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>tbody-tr-td 1</td>
                <td>tbody-tr-td 2</td>
                <td>tbody-tr-td 3</td>
            </tr>
            <tr>
                <td>tbody-tr-td 4</td>
                <td>tbody-tr-td 5</td>
                <td>tbody-tr-td 6</td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td>tfoot-tr-td 1</td>
                <td>tfoot-tr-td 2</td>
                <td>tfoot-tr-td 3</td>
            </tr>
    </table>
</body>

</html>
```
It pastes nicely as 
image

I'm using Windows 10. When I copy, Windows adds meta data to the copied html. I added some logging to show this. The html
before convertTableContent(html) is
```
<html>
<body>
<!--StartFragment--><table style="font-family: &quot;Times New Roman&quot;; letter-spacing: normal; orphans: 2; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><thead><tr><th>thead-tr-th 1</th><th>thead-tr-th 2</th><th>thead-tr-th 3</th></tr></thead><tbody><tr><td>tbody-tr-td 1</td><td>tbody-tr-td 2</td><td>tbody-tr-td 3</td></tr><tr><td>tbody-tr-td 4</td><td>tbody-tr-td 5</td><td>tbody-tr-td 6</td></tr></tbody><tfoot><tr><td>tfoot-tr-td 1</td><td>tfoot-tr-td 2</td><td>tfoot-tr-td 3</td></tr></tfoot></table><!--EndFragment-->
</body>
</html>
```
After that call it's
```
<!--StartFragment--><table style="font-family: &quot;Times New Roman&quot;; letter-spacing: normal; orphans: 2; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><thead><p>thead-tr-th 1 thead-tr-th 2 thead-tr-th 3</p></thead><tbody><p>tbody-tr-td 1 tbody-tr-td 2 tbody-tr-td 3</p><p>tbody-tr-td 4 tbody-tr-td 5 tbody-tr-td 6</p></tbody><tfoot><p>tfoot-tr-td 1 tfoot-tr-td 2 tfoot-tr-td 3</p></tfoot></table><!--EndFragment-->
```
And it ends up as this after the collapse call
```
<p>thead-tr-th 1 thead-tr-th 2 thead-tr-th 3</p><p>tbody-tr-td 1 tbody-tr-td 2 tbody-tr-td 3</p><p>tbody-tr-td 4 tbody-tr-td 5 tbody-tr-td 6</p><p>tfoot-tr-td 1 tfoot-tr-td 2 tfoot-tr-td 3</p><p></p>
```

**Comment by jonmarozick** [comment]
The remove consecutive will clean this up. But I'm thinking of removing the table elements from blockElements and just doing all the processing in convertTableContent(html)

image

**Comment by jonmarozick** [comment]
That is working well. I start with this html
```
<html>
<body>
<!--StartFragment--><table style="font-family: &quot;Times New Roman&quot;; letter-spacing: normal; orphans: 2; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><thead><tr><th>thead-tr-th 1</th><th>thead-tr-th 2</th><th>thead-tr-th 3</th></tr></thead><tbody><tr><td>tbody-tr-td 1</td><td>tbody-tr-td 2</td><td>tbody-tr-td 3</td></tr><tr><td>tbody-tr-td 4</td><td>tbody-tr-td 5</td><td>tbody-tr-td 6</td></tr></tbody><tfoot><tr><td>tfoot-tr-td 1</td><td>tfoot-tr-td 2</td><td>tfoot-tr-td 3</td></tr></tfoot></table><!--EndFragment-->
</body>
</html>
```
After running convertTableContent(html) it's this
```
<!--StartFragment--><p>thead-tr-th 1 thead-tr-th 2 thead-tr-th 3</p><p>tbody-tr-td 1 tbody-tr-td 2 tbody-tr-td 3</p><p>tbody-tr-td 4 tbody-tr-td 5 tbody-tr-td 6</p><p>tfoot-tr-td 1 tfoot-tr-td 2 tfoot-tr-td 3</p><!--EndFragment-->
```
Then this 
image

**Comment by jonmarozick** [comment]
I removed Array.from() since NodeListOf<T> works with forEach()

**Comment by jonmarozick** [comment]
@Artem-Schander  If we can merge this PR sometime this week, that'd be great. I'm trying to beat the July 23 Chrome release which will affect Quill 1.x. https://developer.chrome.com/blog/mutation-events-deprecation

**Comment by enzedonline** [comment]
I'm seeing an error when I paste content with an image from a picture element when the source images have a relative link. There's a GET request to the local server for the pasted image (e.g pasting `https://example.com/media/some-image.jpg`), I see a failed GET request for `https://my-site.com/media/some-image.jpg`). For example, copy the image including the text above and below [here](https://enzedonline.com/en/tech-blog/create-responsive-font-sizes-based-on-the-viewport/#:~:text=This%20gives%20me,sizes%20in%20rem).

To replicate the error at the console:
```javascript
html = `<html><body><!--StartFragment--><div class="block-container" style="box-sizing: border-box; margin-top: 1rem; margin-bottom: 1rem; color: rgb(52, 58, 64); font-family: &quot;Work Sans&quot;, sans-serif; font-size: 16.8625px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="text-center" style="box-sizing: border-box; text-align: center !important;"><p data-block-key="fs5b8" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; font-family: var(--font-family-body); font-size: var(--font-size-body);">This gives me a set of font sizes that looks like the following:</p></div></div><div class="block-container" style="box-sizing: border-box; margin-top: 1rem; margin-bottom: 1rem; color: rgb(52, 58, 64); font-family: &quot;Work Sans&quot;, sans-serif; font-size: 16.8625px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="bg-transparent p-1 mx-auto rounded-3" style="box-sizing: border-box; margin-right: auto !important; margin-left: auto !important; padding: 0.25rem !important; --bs-bg-opacity: 1; background-color: transparent !important; border-radius: var(--bs-border-radius-lg) !important; color: black; max-width: calc(800px + 0.5rem);"><figure class="m-0" style="box-sizing: border-box; margin: 0px !important; max-width: 800px;"><picture style="box-sizing: border-box;"><source media="(max-width: 500px)" sizes="(max-width: 500px) 500px" srcset="/media/images/font-sizes.width-500.format-webp.webp 500w" type="image/webp" style="box-sizing: border-box;"><source media="(max-width: 750px)" sizes="(max-width: 750px) 750px" srcset="/media/images/font-sizes.width-750.format-webp.webp 750w" type="image/webp" style="box-sizing: border-box;"><source media="(max-width: 1200px)" sizes="(max-width: 1200px) 1200px" srcset="/media/images/font-sizes.width-1200.format-webp.webp 1200w" type="image/webp" style="box-sizing: border-box;"><source media="(max-width: 1600px)" sizes="(max-width: 1600px) 1600px" srcset="/media/images/font-sizes.width-1600.format-webp.webp 1600w" type="image/webp" style="box-sizing: border-box;"><source media="(min-width: 1601px)" sizes="(min-width: 1601px) 1601px" srcset="/media/images/font-sizes.width-1800.format-webp.webp 1800w" type="image/webp" style="box-sizing: border-box;"><img src="https://enzedonline.com/media/images/font-sizes.original.png" alt="graph showing the range of minimum and maximum font sizes for standard text elements" class="image-w-100-auto" style="box-sizing: border-box; vertical-align: middle; width: 758px; height: auto;"></picture></figure></div></div><!--EndFragment--></body></html>`
tempDiv = document.createElement('div');
tempDiv.innerHTML = html;
```
Output (Windows):
```
GET file:///C:/media/images/font-sizes.width-750.format-webp.webp net::ERR_FILE_NOT_FOUND
```

Seems setting the innerHTML to the tempDiv's in `collapseConsecutiveSubstitutionTags`, `tableHeadersToCells` & `convertTableContent` is triggering a GET request for those resources each time. Because of the relative links, it tries to resolve to the local server.

The error isn't triggered in `collapseConsecutiveSubstitutionTags` since the html has been sanitized by that point.

There's a quick fix to convert the HTML with a DOMParser instead of setting innerHTML. Resolves the error and makes pasting content with remote resources much faster since it's no longer making GET requests on those methods.

```javascript
parser = new DOMParser();
doc = parser.parseFromString(html, 'text/html');
```

```javascript
  collapseConsecutiveSubstitutionTags(html, substitution) {
    // Remove all consecutive occurances of substitution (e.g. <p></p>) from html, include tags with only whitespace
    const parser = new DOMParser()
    const doc = parser.parseFromString(html, 'text/html');
    const tags = doc.querySelectorAll(substitution);
    let removeNextTag = false;
    tags.forEach(tag => {
      if (!removeNextTag) {
        removeNextTag = true;
        return;
      }

      if (tag.firstChild === null || (tag.firstChild.nodeType === 3 && tag.firstChild.nodeValue.trim() === '')) {
        tag.parentNode.removeChild(tag);
      } else {
        removeNextTag = false;
      }
    });
    return doc.body.innerHTML;
  }

  tableHeadersToCells(html) {
    // Quill table doesn't support header cells
    // Move first <tr> from <thead> to <tbody>, convert all <th> to <td>
    const parser = new DOMParser()
    const doc = parser.parseFromString(html, 'text/html');
    const tables = doc.querySelectorAll('table');
    tables.forEach(table => {
      // Check if the table has a <thead> element
      const thead = table.querySelector('thead');
      if (thead) {
        // Move the <thead>'s first <tr> child to be the first child of <tbody>
        const tbody = table.querySelector('tbody');
        if (tbody) {
          const firstRow = thead.querySelector('tr');
          tbody.insertBefore(firstRow, tbody.firstChild);
        }
      }
      // Convert all <th> elements to <td> elements
      const thElements = table.querySelectorAll('th');
      thElements.forEach(th => {
        const td = document.createElement('td');
        td.innerHTML = th.innerHTML;
        th.parentNode.replaceChild(td, th);
      });
    });
    return `<html>${doc.body.outerHTML}<html>`;
  }

  convertTableContent(html) {
    const parser = new DOMParser()
    const doc = parser.parseFromString(html, 'text/html');

    // Convert <tr> elements to <p> elements, concatenate td & th cell contents with inner space added
    doc.querySelectorAll('tr').forEach(tr => {
      tr.outerHTML = `<p>${Array.from(tr.querySelectorAll('td, th')).map(cell => cell.innerHTML).join(' ')}</p>`
    });

    // Convert orphan td & th elements to their innerHTML plus trailing space
    doc.querySelectorAll('td, th').forEach(cell => {
      cell.outerHTML = `${cell.innerHTML} `;
    });
  
    // Collapse thead, tbody, and tfoot elements to their innerHTML
    doc.querySelectorAll('thead, tbody, tfoot').forEach(rowContainers => {
      rowContainers.outerHTML = rowContainers.innerHTML;
    });

    // Collapse table elements to their innerHTML
    doc.querySelectorAll('table').forEach(tableEle => {
      tableEle.outerHTML = tableEle.innerHTML;
    });

    return `<html>${doc.body.outerHTML}<html>`;
  }
```

**Comment by jonmarozick** [comment]
Nice find @enzedonline. I made the changes, and everything works well.

**Comment by enzedonline** [comment]
@Artem-Schander Is there anything remaining holding back this PR?

**Comment by artem-schander** [comment]
@enzedonline 
No, there is nothing holding back this PR. I just waited to get a final info of it being complete.
I'm not sure if it's a better idea to create a v2 branch with the contents of this PR or a v1 branch with the contents of the current master branch.

Besides that, I never thought this package would gain traction, therefore I didn't implement any tests. I think it's about time to get them done.

Many thanks to both of you for the great work you have done 👍

**Comment by enzedonline** [comment]
It's a great package - thanks for the doing all the work for the first version :) Nice to find a Quill package that hasn't been abandoned for once 😂

> I'm not sure if it's a better idea to create a v2 branch with the contents of this PR or a v1 branch with the contents of the current master branch.

Probably best to just release with new major version no? v2.0.0 as per package.json?

This package is on Quill's list of [recommended modules](https://github.com/quilljs/awesome-quill) which is where I found it, probably why it got so much traction ;)

Quite a few of those are not compatible with Quill v2. I've just pr'd the v2 version of quill-image-compress, that's released there now. 

quill-blot-formatter hasn't been updated in years, I guess it's abandoned now. I've re-written it and released a v2 compatible version [here](https://github.com/enzedonline/quill-blot-formatter2) in case you need an image formatter - the alignment actions on the old version weren't working with Quill v2. I'm on the last stages of a newer version adding alt/title capability which will allow floating captions on images. Should be done by the end of the week.

If you need tables, I'd recommend quill-better-tables-plus. quill-better-tables has issues with v2 and seems to be abandoned as well.

**Comment by artem-schander** [comment]
> Probably best to just release with new major version no? v2.0.0 as per package.json?

That was the plan anyway.
What I meant is that to ensure continuous work on both versions, there should be a clear structure in the git repo.
I decided to create a "legacy" branch vor the v1.

> If you need tables, I'd recommend quill-better-tables-plus. quill-better-tables has issues with v2 and seems to be abandoned as well.

I've been looking for a table plugin a while ago. Thanks

**Comment by artem-schander** [comment]
Here you go [v2](https://www.npmjs.com/package/quill-paste-smart/v/2.0.0)
Thanks again

**Pull request merged**
